language: node_js
branches:
  only:
  - hexo #源码分支名称
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'kapokhui'
- git config --global user.email '371517961@qq.com'
- sed -i'' "s~git@github.com:kapokhui/kapokhui.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/kapokhui/kapokhui.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
